my-wpdb:
  image: mariadb
  ports:
    - "8081:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant

my-wp:
  image: wordpress
  volumes:
    - ./test-theme:/var/www/html/wp-content/themes/test-theme
  ports:
    - "8080:80"
  links:
    - my-wpdb:mysql
  environment:
    DB_HOST: my-wpdb
    DB_NAME: wordpress
    DP_PASS: ChangeMeIfYouWant
    WP_DEBUG: 'true'
