version: '2'

services:
  my-wp:
    image: wordpress
    volumes:
      - ./test-theme:/var/www/html/wp-content/themes/test-theme
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant

volumes:
  test-theme:
